apiVersion: v1
kind: Service
metadata:  
  name: cfostest-headless
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  selector:
    app: firewall
  ports:    
    - protocol: TCP
      port: 8080
      targetPort: 8080

