apiVersion: v1
data:
  config: |-
    config log syslogd setting
      set status enable
      set server "fazcfos2025.eastus.cloudapp.azure.com"
      set interface "eth0"
    end
    config webfilter profile
    edit "demo1"
        config ftgd-wf
            set options error-allow
        end
    end
    config application list
      edit "demo1"
        set comment "block http file upload"
        set extended-log enable
          config entries
             edit 1
                set category 15
                set application 18123
                set action block
             next
             edit 2
                set category 15
                set application 17136
                set action block
             next
          end
      next
    end
    config firewall policy
        edit 300
            set utm-status enable
            set name "policy-name"
            set srcintf "vxlan0"
            set dstintf "eth0"
            set srcaddr "protectedpodtest"
            set dstaddr "all"
            set service "ALL"
            set ssl-ssh-profile "mytest"
            set av-profile "default"
            set webfilter-profile "default"
            set ips-sensor "default"
            set application-list "demo1"
            set nat enable
            set custom-log-fields "pod-label" "nodeip" "nodename" "firewalllabel"
            set logtraffic all
        next
    end
  type: partial
kind: ConfigMap
metadata:
  labels:
    app: fos
    category: config
  name: demo1configmap
