apiVersion: v1
data:
  config: |-
    config webfilter profile
    edit "default"
        config ftgd-wf
            set options error-allow
        end
    end
  type: partial
kind: ConfigMap
metadata:
  labels:
    app: fos
    category: config
  name: webprofileerrorpass
  namespace: default
