deployment:
  kind: Deployment  # Can be set to "Deployment" if needed
replicaCount: 1    # Only used if kind is Deployment
updateStrategy: RollingUpdate

persistence:
  enabled: false
  # existingClaim: cfosconfigdata  # Uncomment to use existing PVC
  # If not using existing claim, below values are used to create a new PVC
  storageClass: "local-path"
  accessMode: ReadWriteOnce
  size: 1Gi

enablecFOSAPI8080: false
image:
  repository: public.ecr.aws/t8s9q7q9/andy2024public
  tag: cfosx86v255

resources:
  requests:
    cpu: 500m
    memory: 512Mi

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: cfos-serviceaccount
  annotations: {}
  imagePullSecrets: []

nodeSelector:
  security: "true"

initContainers:
  enabled: true
  image:
    repository: busybox
    tag: latest
    pullPolicy: IfNotPresent

dnsConfig:
  nameserver: "10.96.0.10"
  searchDomains:
    - "default.svc.cluster.local"
    - "svc.cluster.local"
    - "cluster.local"

securityContext:
  allowPrivilegeEscalation: true
  privileged: false
  capabilities:
    add: 
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
      - BPF 

appArmor:
  enabled: false
  profile: "unconfined"

podAnnotations: {}

service:
  type: ClusterIP
  port: 443

ingress:
  enabled: false

autoscaling:
  enabled: false
  name: cfoshpa
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 70
  scaleUp:
    stabilizationWindowSeconds: 60
    percentValue: 100
    periodSeconds: 60
  scaleDown:
    stabilizationWindowSeconds: 300
    percentValue: 100
    periodSeconds: 60

labels:
  app: firewall

api:
  port: 8080
  nodePort:
    enabled: true
    serviceName: "cfos-api-service"
    port: 31943

routeManager:
  enabled: true
  image:
    repository: public.ecr.aws/t8s9q7q9/andy2024public
    tag: cni0.1.23
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
    name: cni-service-account
  env:
    INTERFACE_TYPE: "vxlan"
    FIREWALL_LABEL: "app=firewall"
    PROTECTED_LABEL: "protectedby=cfos"
    FIREWALL_VXLAN_IP: "192.168.200.250"
    PROTECTED_VXLAN_BASE_IP: "192.168.200."
    FIREWALL_VLAN_IP: "192.168.200.250"
    VLAN_ID: "100"
    VXLAN_ID: "42"
    ROUTE_DST: "0.0.0.0/1,128.0.0.0/1"
    LOG_LEVEL: "extendedDebug"
    BPF_FS_PATH: "/sys/fs/bpf"  # Added BPF filesystem path
    EBPF_PROGRAM_PATH: "./myapp.bpf.o"
    EBPF_MAP_PATH: "/sys/fs/bpf/myapp"
    EBPF_ATTACH_IFACE: "cni0"
    DEFAULT_FIREWALL_POLICY: "UTM"

bpf:
  enabled: true  # Enable BPF filesystem mounting

kedaScaling:
  enabled: false
  installKeda: false  # Set to true to install KEDA as a dependency
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicas: 1
  maxReplicas: 5
  triggers:
    cpu:
      enabled: true
      targetValue: "80"
    memory:
      enabled: true
      targetValue: "300000000"
    sessionCount:
      enabled: true
      targetValue: "100"

metrics:
  service:
    enabled: true
    type: ClusterIP
    port: 8080

