deployment:
  kind: DaemonSet  # Can be set to "Deployment" if needed
replicaCount: 1    # Only used if kind is Deployment
updateStrategy: RollingUpdate

image:
  repository: public.ecr.aws/t8s9q7/q9/andy2024public
  tag: cfosx86v255

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: cfos-serviceaccount
  annotations: {}
  imagePullSecrets: []

nodeSelector:
  security: "true"

initContainers:
  enabled: true
  image:
    repository: busybox
    tag: latest
    pullPolicy: IfNotPresent

dnsConfig:
  nameserver: "10.96.0.10"
  searchDomains:
    - "default.svc.cluster.local"
    - "svc.cluster.local"
    - "cluster.local"

securityContext:
  allowPrivilegeEscalation: true
  privileged: false
  capabilities:
    add: 
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW

appArmor:
  enabled: false
  profile: "unconfined"

podAnnotations: {}

service:
  type: ClusterIP
  port: 443

ingress:
  enabled: false

autoscaling:
  enabled: false

labels:
  app: firewall

routeManager:
  enabled: true
  image:
    repository: public.ecr.aws/t8s9q7q9/andy2024public
    tag: cni0.1.13
    pullPolicy: Always
  serviceAccount:
    create: true
    name: cni-service-account
  env:
    INTERFACE_TYPE: "vxlan"
    FIREWALL_LABEL: "app=firewall"
    PROTECTED_LABEL: "protectedby=cfos"
    FIREWALL_VXLAN_IP: "192.168.200.250"
    PROTECTED_VXLAN_BASE_IP: "192.168.200."
    FIREWALL_VLAN_IP: "192.168.200.250"
    VLAN_ID: "100"
    VXLAN_ID: "42"
    ROUTE_DST: "0.0.0.0/1,128.0.0.0/1"
    LOG_LEVEL: "extendedDebug"
