{{- if and .Values.autoscaling.enabled (ne .Values.deployment.kind "DaemonSet") }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.autoscaling.name | default (include "cfos.fullname" .) }}
  labels:
    {{- include "cfos.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.deployment.kind | default "Deployment" }}
    name: {{ include "cfos.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas | default 10 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage | default 50 }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage | default 70 }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleUp.stabilizationWindowSeconds | default 60 }}
      policies:
      - type: Percent
        value: {{ .Values.autoscaling.scaleUp.percentValue | default 100 }}
        periodSeconds: {{ .Values.autoscaling.scaleUp.periodSeconds | default 60 }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleDown.stabilizationWindowSeconds | default 300 }}
      policies:
      - type: Percent
        value: {{ .Values.autoscaling.scaleDown.percentValue | default 100 }}
        periodSeconds: {{ .Values.autoscaling.scaleDown.periodSeconds | default 60 }}
{{- end }}
