{{- if and .Values.kedaScaling.enabled .Values.cFOSmetricExample.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cfos.fullname" . }}-metrics-config
  labels:
    {{- include "cfos.labels" . | nindent 4 }}
    app: cfos
  annotations:
    cfos.fortinet.com/config-type: metrics
data:
  metrics: |
    [
      {
        "type": "resource",
        "name": "cpu_usage",
        "collection": "prometheus",
        "labels": {
          "resource_type": "cpu"
        }
      },
      {
        "type": "resource",
        "name": "memory_usage",
        "collection": "prometheus",
        "labels": {
          "resource_type": "memory"
        }
      },
      {
        "type": "cli",
        "name": "session_count",
        "query": "conntrack -C",
        "collection": "prometheus",
        "labels": {
          "metric_type": "system"
        }
      }
    ]
{{- end }}
