name: Publish Helm chart

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0

    - name: Install chart-releaser
      run: |
        wget https://github.com/helm/chart-releaser/releases/download/v1.4.0/chart-releaser_1.4.0_linux_amd64.tar.gz
        tar xzvf chart-releaser_1.4.0_linux_amd64.tar.gz cr
        sudo mv cr /usr/local/bin/cr

    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages-branch

    - name: Package and Release
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p .cr-release-packages
        helm package cfos -d .cr-release-packages
        cr upload -o yagosys -r cfos-chart --token "$CR_TOKEN" --skip-existing
        
        # Merge new and existing packages
        cp gh-pages-branch/*.tgz .cr-release-packages/ || true
        
        # Update index file
        cr index -o yagosys -r cfos-chart -c https://yagosys.github.io/cfos-chart/ --token "$CR_TOKEN"

    - name: Move files for GitHub Pages
      run: |
        mkdir -p gh-pages
        cp .cr-release-packages/*.tgz gh-pages/
        cp .cr-index/index.yaml gh-pages/
        touch gh-pages/.nojekyll

    - name: Push to GitHub Pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        # Remove force_orphan option
